spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.0.22:1521:XE
    username: ljy
    password: ljy1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace